Fix Estonian PPPP date format
The date format for PPPP token in locales use "EEEE" instead of
"eeee". Using "eeee" in Estonian was leading to the following
error:

```
RangeError: The format string mustn't contain `eeee` and `d` at the same time
    at parse (/.../node_modules/date-fns/parse/index.js:458:17)
```